### ISSUE TITLE
Running tool_use.ipynb returns error

### ISSUE THREAD

**Issue by mjedmonds** [guidance-ai/guidance#310] opened 2023-07-12 03:18 UTC
**The bug**

Running [tool_use.ipynb](https://github.com/microsoft/guidance/blob/main/notebooks/art_of_prompt_design/tool_use.ipynb) results in the following error when attempting to create the program:

```
File guidance/_program_executor.py:36), in replace_partial(match)
     23 self.llm_session = None
     24 self._logging = hasattr(self.program.log, "append")
     26 # find all the handlebars-style partial inclusion tags and replace them with the partial template
     27 # def replace_partial(match):
     28 #     parts = match.group(1).split(" ", 1)
     29 #     partial_name = parts[0]
     30     
     31 #     # ,args_string = match.group(1).split(" ", 1)
     32 #     if partial_name not in program._variables:
     33 #         raise ValueError("Partial '%s' not given in the keyword args:" % partial_name)
     34 #     out = "{{#block '"+partial_name+"'"
     35 #     if len(parts) > 1:
---> 36 #         out += " " + parts[1]
     37 #     out += "}}" + program._variables[partial_name].text + "{{/block}}"
     38 #     # Update the current program variables using those from the partial, but do not overwrite.
     39 #     # (Rebuilding the _variables map here would break returning new values to the program variables later, e.g. from gen.)
     40 #     update_variables = {
     41 #         k: v
     42 #         for k, v in program[partial_name]._variables.items()
     43 #         if k not in program._variables
     44 #     }
     45 #     program._variables.update(update_variables)
     46 #     return out
     47 # text = re.sub(r"{{>(.*?)}}", replace_partial, program._text)
     48 
     49 # parse the program text
     50 try:
     51     self.parse_tree = grammar.parse_string(program._text)

ValueError: Partial '@tool_def' not given in the keyword args:
```

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
1. Run [tool_use.ipynb](https://github.com/microsoft/guidance/blob/main/notebooks/art_of_prompt_design/tool_use.ipynb) 

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Mac OS
 - Guidance Version (`guidance.__version__`): 0.0.64

**Comment by mjedmonds** [comment] 2023-07-12 03:19
@slundberg I think you may have insight into this one based on previous contributions!

**Comment by yakigac** [comment] 2023-07-22 10:47
As a fellow user trying to understand this issue, I couldn't reproduce the error in Google Colaboratory.

Could you specify the cell in the Jupyter notebook where the error occurs? This could help us understand the issue more precisely.

**Comment by marcotcr** [comment] 2023-11-14 22:21
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where tool use is _much_ better and easier. Sorry it took us so long to get to it!

**Closed by marcotcr** 2023-11-14 22:21 UTC
