### ISSUE TITLE
result: {{G|138083605991872|G}}

### ISSUE THREAD

**Issue by wiiiktor** [guidance-ai/guidance#501] opened 2023-12-03 14:27 UTC
I sometimes have this result (on Kaggle or Colab) when using LlamaCpp or some HuggingFace(Llama) model: 

<img width="455" alt="image" src="https://github.com/guidance-ai/guidance/assets/41764319/aeaa5d34-dc50-48e2-a24e-b1b58f5be299">

**Comment by slundberg** [comment] 2023-12-11 23:53
I am going to close this now since things seems to be working as intended. (note also that the result of this operation is now a grammar object as opposed to a delayed call string like shown above)

**Closed by slundberg** 2023-12-11 23:53 UTC
