### ISSUE TITLE
[BUG] Get Error When Using gen() with list_append=True in Guidance Server

### ISSUE THREAD

**Issue by stonekim** [guidance-ai/guidance#920] opened 2024-06-22 16:28 UTC
**The bug**
  File "/opt/homebrew/lib/python3.9/site-packages/guidance/models/_model.py", line 116, in encode
    return self.serialize()
  File "/opt/homebrew/lib/python3.9/site-packages/guidance/models/_model.py", line 119, in serialize
    proto = self._to_proto()
  File "/opt/homebrew/lib/python3.9/site-packages/guidance/models/_model.py", line 105, in _to_proto
    return _serialization_pb2.EngineCallResponse(
  File "/opt/homebrew/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 531, in init
    copy.update(field_value)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_collections_abc.py", line 941, in update
    self[key] = other[key]
  File "/opt/homebrew/lib/python3.9/site-packages/google/protobuf/internal/containers.py", line 431, in __setitem__
    checked_value = self._value_checker.CheckValue(value)
  File "/opt/homebrew/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 211, in CheckValue
    raise TypeError(message)
TypeError: [b'The '] has type <class 'list'>, but expected one of: (<class 'bytes'>, <class 'str'>)

**To Reproduce**

```python
from guidance import select
from guidance import models, gen, with_temperature
llama2 = models.LlamaCpp("http://localhost:8392", api_key="SDFSDF")

query = "Who won the last Kentucky derby and by how much?"
lm = llama2 + f'''\
Q: {query}
Now I will choose to either SEARCH the web or RESPOND.
Choice: {select(["SEARCH", "RESPOND"], name="choice")}
'''
if lm["choice"] == "SEARCH":
    lm += "Here are 3 search queries:\n"
    for i in range(3):
        lm += f'''{i+1}. "{gen(stop='"', name="queries", temperature=1.0, list_append=True)}"\n'''
```

**Comment by Dobiichi-Origami** [comment] 2024-06-24 06:39
I came up a way to fix it:
Modify your code of relative functions in guidance.models._model.py.EngineCallResponse like this:
```
    def _to_proto(self):
        """Converts an EngineCallResponse object to its Protobuf representation.

        Returns:
            engine_response_pb2.EngineCallResponse: The Protobuf equivalent of this object.
        """
        groups = {}
        group_log_probs = {}

        log_probs_list_prefix = "__LOGS_PROBS_LIST_"

        for k, v in self.capture_groups.items():
            if not isinstance(v, list):
                groups[k] = v
                group_log_probs[k] = self.capture_group_log_probs[k]
                continue

            groups[k] = json.dumps([str(value, encoding="utf8") for value in v])

            for i, numeric_value in enumerate(self.capture_group_log_probs[k]):
                group_log_probs["{}_{}_{}".format(log_probs_list_prefix, k, i)] = numeric_value

        return _serialization_pb2.EngineCallResponse(
            new_bytes=self.new_bytes,
            is_generated=self.is_generated,
            new_bytes_prob=self.new_bytes_prob,
            capture_groups=groups,
            capture_group_log_probs=group_log_probs,
            new_token_count=self.new_token_count,
        )

    @staticmethod
    def deserialize(byte_data):
        proto = _serialization_pb2.EngineCallResponse()
        proto.ParseFromString(byte_data)

        groups = {}
        group_log_probs = {}

        log_probs_list_prefix = "__LOGS_PROBS_LIST_"

        for k, v in proto.capture_groups.items():
            groups[k] = [bytes(value, encoding="utf8") for value in json.loads(v)]
            if isinstance(groups[k], list):
                group_log_probs[k] = []
                for i in range(len(groups[k])):
                    key_name = "{}_{}_{}".format(log_probs_list_prefix, k, i)
                    group_log_probs[k].append(proto.capture_group_log_probs[key_name])
            else:
                group_log_probs = proto.capture_group_log_probs[k]


        return EngineCallResponse(
            new_bytes=proto.new_bytes,
            is_generated=proto.is_generated,
            new_bytes_prob=proto.new_bytes_prob,
            capture_groups=groups,
            capture_group_log_probs=group_log_probs,
            new_token_count=proto.new_token_count,
        )
```

**Comment by hudson-ai** [comment] 2024-06-24 17:19
@stonekim thanks for raising the issue and @Dobiichi-Origami thanks for the workaround!

@nking-1 it looks like the issue is that the protocol expects the values of the `capture_groups` and `capture_groups_log_probs` dicts to be bytes/strings and floats respectively, while we need to support the union of those and list-ified versions of that. Is this a corner of the codebase you're familiar with/could help out with?

**Comment by nking-1** [comment] 2024-06-24 19:39
I'm vaguely familiar with this code. I'll take a look today.

**Comment by nking-1** [comment] 2024-06-25 00:14
Quick update - I looked over this today and made some progress toward reproducing the issue, along with generating new protobuf definitions. I'd say I'm about halfway through understanding the fix for this. 

The bug only seems to occur when running a guidance server. I didn't see any issues when running `gen` with `list_append=True` otherwise.

**Comment by hudson-ai** [comment] 2024-06-25 01:30
Thank you @nking-1 !

**Comment by stonekim** [comment] 2024-07-01 03:48
Thank you @nking-1 @hudson-ai  ! 
May I ask if there is an update to fix this issue? We urgently need this feature.

**Comment by hudson-ai** [comment] 2024-07-02 23:29
@stonekim see the newly linked PR :)

**Closed** 2024-07-03 21:48 UTC
